//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEtudiant.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etudiant
    {
        public int idPers { get; set; }
        public string Genre { get; set; }
        public string Filiere { get; set; }
        public string Niveau { get; set; }
    }
}
